require 'rake'
require 'rake/clean'
require 'rubygems'
require 'rubygems/gem_runner'
require 'geminabox_client'

spec = eval(File.read(Dir['*.gemspec'][0]))

SUDO = (ENV['sudo'] =~ /(true|t|yes|y|1)$/i) && 'sudo' || ''

CLOBBER.include '*.gem'

task :default => :build

task :build => :gem

task :gem do
	puts in_green "Create #{spec.summary} Gem"
	Gem::GemRunner.new.run ['build', "#{spec.name}.gemspec"]
end

task :install => :gem do
	puts in_green "Install #{spec.summary} Gem"
	Gem::GemRunner.new.run ['install', "#{spec.name}-#{spec.version}.gem", '--local']
end

task :uninstall do
	puts in_green "Uninstalling #{spec.summary} Gem"
	Gem::GemRunner.new.run ['uninstall', "#{spec.name}"]
end

task :release => :build do
	puts in_green "Uploading #{spec.summary} Gem to Local Repository"
	GeminaboxClient.new(ENV['GEM_REPOSITORY']).push "#{spec.name}-#{spec.version}.gem"
end

def in_green txt
	"\x1b[32m#{txt}\x1b[0m"
end
