require 'rake'
require 'rake/clean'
require 'lib/rubydin/version'

name = 'Rubydin'
file = 'rubydin'
version = Rubydin::VERSION

SUDO = (ENV['sudo'] =~ /(true|t|yes|y|1)$/i) && 'sudo' || ''
BUILD_DIR = 'build'
CLASSES_DIR = 'build/classes'

CLOBBER.include BUILD_DIR, CLASSES_DIR, '*.gem'

task :default => :build

task :build => [:jar, :gem]

task :gem do
	mkdir BUILD_DIR unless Dir.exists? BUILD_DIR
	puts in_green "Create #{name} Gem"
	FileUtils.cp "build/rubydin-#{version}.jar", 'lib/java'
	shell "jruby -S gem build #{file}.gemspec"
	FileUtils.rm "lib/java/rubydin-#{version}.jar"
end

task :jar do
	mkdir BUILD_DIR unless Dir.exists? BUILD_DIR
	mkdir CLASSES_DIR unless Dir.exists? CLASSES_DIR
	puts in_green "Compiling #{name} Jar"
	sources = Dir['src/**/*.java'].join ' '
	classpath = Dir['lib/java/*.jar'].join File::PATH_SEPARATOR
	shell "javac -cp src:#{classpath} -d #{CLASSES_DIR} -source 1.6 -target 1.6 -Xlint:unchecked #{sources}"
	shell "jar -cfv #{BUILD_DIR}/#{file}-#{version}.jar -C #{CLASSES_DIR} ."
end

task :install => :build do
	puts in_green "Install #{name} Gem"
	shell "${SUDO} jruby -S gem install #{file}-#{version}.gem"
end

task :uninstall do
	puts in_green "Uninstalling #{name} Gem"
	shell "${SUDO} jruby -S gem uninstall #{file}"
end

def shell cmd
	IO.popen("#{cmd} 2>&1", 'r') {|out| out.each {|line| puts "  #{line}"}}
end

def in_green txt
	"\x1b[32m#{txt}\x1b[0m"
end