require 'rake'
require 'rake/clean'
require 'rubygems'
require 'rubygems/gem_runner'
require 'geminabox_client'

spec = eval(File.read(Dir['*.gemspec'][0]))

SUDO = (ENV['sudo'] =~ /(true|t|yes|y|1)$/i) && 'sudo' || ''
BUILD_DIR = 'build'
CLASSES_DIR = 'build/classes'

CLOBBER.include BUILD_DIR, CLASSES_DIR, '*.gem'

task :default => :build

task :build => [:jar, :gem]

task :gem do
	mkdir BUILD_DIR unless Dir.exists? BUILD_DIR
	puts in_green "Create #{spec.summary} Gem"
	FileUtils.cp "build/rubydin-#{spec.version}.jar", 'lib/java'
	Gem::GemRunner.new.run ['build', "#{spec.name}.gemspec"]
	FileUtils.rm "lib/java/rubydin-#{spec.version}.jar"
end

task :jar do
	mkdir BUILD_DIR unless Dir.exists? BUILD_DIR
	mkdir CLASSES_DIR unless Dir.exists? CLASSES_DIR
	puts in_green "Compiling #{spec.summary} Jar"
	sources = Dir['src/**/*.java'].join ' '
	classpath = Dir['lib/java/*.jar'].join File::PATH_SEPARATOR
	shell "javac -cp src:#{classpath} -d #{CLASSES_DIR} -source 1.6 -target 1.6 -Xlint:unchecked #{sources}"
	shell "jar -cfv #{BUILD_DIR}/#{spec.name}-#{spec.version}.jar -C #{CLASSES_DIR} ."
end

task :install => :build do
	puts in_green "Install #{spec.summary} Gem"
	Gem::GemRunner.new.run ['install', "#{spec.name}-#{spec.version}.gem", '--local']
end

task :uninstall do
	puts in_green "Uninstalling #{spec.summary} Gem"
	Gem::GemRunner.new.run ['uninstall', "#{spec.name}"]
end

task :release => :build do
	puts in_green "Uploading #{spec.summary} Gem to Local Repository"
	GeminaboxClient.new(ENV['GEM_REPOSITORY']).push "#{spec.name}-#{spec.version}.gem"
end

def shell cmd
	IO.popen("#{cmd} 2>&1", 'r') {|out| out.each {|line| puts "  #{line}"}}
end

def in_green txt
	"\x1b[32m#{txt}\x1b[0m"
end