require 'rake'
require 'rake/clean'
require 'lib/rubydin-optional-standalone/version'

name = 'Rubydin Optional Standalone Server'
file = 'rubydin-optional-standalone'
version = Rubydin::VERSION_STANDALONE

SUDO = (ENV['sudo'] =~ /(true|t|yes|y|1)$/i) && 'sudo' || ''

CLOBBER.include '*.gem'

task :default => :build

task :build => :gem

task :gem do
	puts in_green "Create #{name} Gem"
	shell "jruby -S gem build #{file}.gemspec"
end

task :install => :gem do
	puts in_green "Install #{name} Gem"
	shell "${SUDO} jruby -S gem install #{file}-#{version}.gem"
end

task :uninstall do
	puts in_green "Uninstalling #{name} Gem"
	shell "${SUDO} jruby -S gem uninstall #{file}"
end

def shell cmd
	IO.popen("#{cmd} 2>&1", 'r') {|out| out.each {|line| puts "  #{line}"}}
end

def in_green txt
	"\x1b[32m#{txt}\x1b[0m"
end
